package com.usbaitass.greetgo.demotest.dao;


import com.usbaitass.greetgo.demotest.mapper.DataMapper;
import com.usbaitass.greetgo.demotest.model.Data;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@Repository
public class DataDaoImpl implements DataDao {

    @Autowired
    DataMapper dataMapper; // bean will be generated by MyBatis

    @Override
    public Data findById(long id) {
        return dataMapper.findById(id);
    }
}
